### ISSUE TITLE
4.5 release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2156]
1. [ ] Wait until Bot Framework SDK release 4.5 RC
1. [ ] Bump Bot Framework SDK in [MockBot](https://github.com/compulim/BotFramework-WebChat)
1. [ ] Build Web Chat from `master` locally
1. Automated testing
   1. [ ] Run `npm test` (with Docker) to test Web Chat
1. Manual testing
   1. [ ] All MockBot commands
      1. Type `help` to MockBot, it will list out all commands
      1. Try out each of the command, list out all failed below, if any
   1. Speech scenarios
      1. [ ] Happy path
         1. Click microphone button and say something
         1. Expect: bot to speak
         1. Expect: microphone to turn on automatically after bot message is spoken
      1. [ ] Turning off microphone
         1. Click microphone button and say something
         1. Expect: while your speech is getting recognized, the microphone button should turn red
         1. Expect: while the microphone button is red, you can click to stop it
         1. Expect: your speech interims should not be sent
      1. [ ] Keyboard interrupted speech synthesis and recognition
         1. Click microphone button and say something
         1. While the bot is speaking, type something on the keyboard
         1. Expect: bot stop speaking immediately and microphone will not turn on by itself
      1. [ ] Unrecognizable sound (or muted microphone)
         1. Click microphone button and do not say anything
         1. Expect: after a few seconds, the microphone button should be switched off by itself
   1. Connectivity scenarios
      1. [ ] Airplane mode
      1. [ ] Bad secret or token
   1. PRs that need to be manually tested because lack of automated tests
      1. [ ] #2016 
      1. [ ] #2018 
      1. [ ] #2087 
      1. [ ] #2090 
      1. [ ] #2096 
      1. [ ] #2118

**Comment by corinagum** [comment]
Updated with PRs needing manual testing

**Comment by sgellock** [comment]
assigned this to an engineer so it's not floated unassigned.  revector to chris or whomever if it's not you William.

**Comment by corinagum** [comment]
Testing on old SDK bits per compulim's request:

~1. [ ] Wait until Bot Framework SDK release 4.5 RC~
~1. [ ] Bump Bot Framework SDK in [MockBot](https://github.com/compulim/BotFramework-WebChat)~
1. [x] Build Web Chat from `master` locally
1. Automated testing
   1. [x] Run `npm test` (with Docker) to test Web Chat
1. Manual testing
   1. [x] All MockBot commands
      1. Type `help` to MockBot, it will list out all commands
      1. Try out each of the command, list out all failed below, if any
   1. Speech scenarios
      1. [x] Happy path
         1. Click microphone button and say something
         1. Expect: bot to speak
         1. Expect: microphone to turn on automatically after bot message is spoken
      1. [x] Turning off microphone
         1. Click microphone button and say something
         1. Expect: while your speech is getting recognized, the microphone button should turn red
         1. Expect: while the microphone button is red, you can click to stop it
         1. Expect: your speech interims should not be sent
      1. [x] Keyboard interrupted speech synthesis and recognition
         1. Click microphone button and say something
         1. While the bot is speaking, type something on the keyboard
         1. Expect: bot stop speaking immediately and microphone will not turn on by itself
      1. [x] Unrecognizable sound 
         1. Click microphone button and do not say anything
         1. Expect: after a few seconds, the microphone button should be switched off by itself
   1. Connectivity scenarios
      1. [x] Airplane mode
      1. [x] Bad secret or token
   1. PRs that need to be manually tested because lack of automated tests
      1. [ ] #2016 
      1. [ ] #2018 
      1. [ ] #2087 
      1. [ ] #2090 
      1. [ ] #2096 
      1. [ ] #2118

**Comment by compulim** [comment]
This is done. 😉
