### ISSUE TITLE
Post-release checklist (4.6 and beyond)

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2161]
These are chores that we should do before starting the cycle to reduce ripple effects if we do it in mid-cycle.

## Applies to all cycles

This list should be copied to versions in the future.
- [x] Make sure `package.json` is `4.5.1-0`
- [x] Bump all dev tool chain to latest version
   - [x] All NPM packages (`@babel/*`, `jest`, `lerna`, `typescript`, `webpack`, etc)
   - [x] Docker container for headless Chrome
- [x] Run `npm audit fix` to make sure everything is fixed
   - 2019-07-13 `lodash` vulnerability is reported on Snyk + GitHub but not on `npm audit` yet, need to wait for a few days
- [x] Verify the build works minimally
- [x] Update [`servicingPlan.json`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/servicingPlan.json)
   - `curl https://cdn.botframework.com/botframework-webchat/4.5.0/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
- [x] Create a new release on GitHub Releases
- [x] Bump React, Redux, and related dependencies to latest version
- [x] ~Bump Adaptive Cards to latest version~ (already on latest 1.2.0)

## Applies to 4.6 only

This list can be copied to versions in the future.

- [x] Bump React to `>= 16.8.0` and `< 17` for React hooks support
   - Just bump version in a single simple PR
   - Then we work on functional component and spread the work across the team
   - Methods that need to be updated from unsafe legacy methods:
      - `BasicWebChat.js`: `UNSAFE_componentWillReceiveProps`
      - `Composer.js`: `UNSAFE_componentWillMount`
      - `ConnectivityStatus`: `UNSAFE_componentWillReceiveProps`
      - `TimeAgo`:  `UNSAFE_componentWillReceiveProps`
      - `Timer`: `UNSAFE_componentWillReceiveProps`
- [x] Bump Redux to latest
- [x] ~Bump `react-redux` to `>= 7.1.0` for React hooks support~
   - Bumped `react-redux` to `5.1.1`, will bump to `7.1.0` in #1846
- [x] Consider bumping `markdown-it`
- [x] ~More tests for speech harness: #2158~
   - Removed from post-release because this chore will not impact mid-development
- [x] Update README.md with breaking change regarding speech functionality
