### ISSUE TITLE
4.5.1 Pre-release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2257]
## Build

1. [x] Update `CHANGELOG.md` to mark specific changes in `4.5.1`
1. [x] Run `npm version --no-git-tag-version 4.5.1`
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
1. [x] Download build artifacts
1. [x] Setup a new React app
   1. [x] `npx create-react-app app`
   1. [x] `npm install` the `.tgz` packages from artifact
   1. [x] Run the app and check if everything works
   1. [x] Check <meta> to see the version number should be `4.5.1` and not a pre-release
1. [x] Setup a new HTML file
   1. [x] Add `<script src="webchat.js">`
   1. [x] Run the app and check if everything works
   1. [x] Check <meta> to see the version number should be `4.5.1` and not a pre-release

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] ~Wait until Bot Framework SDK release 4.5 RC~
1. [x] ~Bump Bot Framework SDK in [MockBot](https://github.com/compulim/BotFramework-WebChat)~
1. [x] Manual testing
   1. [x] All MockBot commands
      1. Type `help` to MockBot, it will list out all commands
      1. Try out each of the command, list out all failed below, if any
      1. Test all of these commands on Internet Explorer 11, as well
   1. [x] Speech scenarios
      1. [x] Happy path
         1. Click microphone button and say something
         1. Expect: bot to speak
         1. Expect: microphone to turn on automatically after bot message is spoken
      1. [x] Turning off microphone
         1. Click microphone button and say something
         1. Expect: while your speech is getting recognized, the microphone button should turn red
         1. Expect: while the microphone button is red, you can click to stop it
         1. Expect: your speech interims should not be sent
      1. [x] Keyboard interrupted speech synthesis and recognition
         1. Click microphone button and say something
         1. While the bot is speaking, type something on the keyboard
         1. Expect: bot stop speaking immediately and microphone will not turn on by itself
      1. [x] Unrecognizable sound (or muted microphone)
         1. Click microphone button and do not say anything
         1. Expect: after a few seconds, the microphone button should be switched off by itself
      1. [x] Test on iOS devices
   1. [x] Connectivity scenarios
      1. [x] Airplane mode
      1. [x] Bad secret or token
   1. [x] PRs that need to be manually tested because lack of automated tests
      1. [x] Test Adaptive Cards in IE11
      1. [x] Test accessibility with a custom Adaptive Card JSON
   1. [x] Test the following with Edge and Narrator:
      1. [x] Adaptive Card
      1. [x] Download attachment
      1. [x] Audio attachment
      1. [x] Video attachment
      1. [x] Image attachment 
      1. [x] Typing indicator
      1. [x] Text content

## Release

1. [x] Make sure you are on `master` or `qfe` branch, run `git status` to check
1. [x] `git pull`
1. [x] `git tag v4.5.1`
1. [x] `git push -u upstream v4.5.1`
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.5.1/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
1. [x] Kick off release to NPM
1. [x] Kick off release to CDN
   1. [x] Send reminder email to approvers
1. [x] Update [`servicingPlan.json`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/servicingPlan.json)
   - Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.5.1/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`

## Post-release check

1. [x] Setup a new React app using the package from NPM
1. [x] Setup a new HTML file using the bundle from CDN

**Comment by compulim** [comment]
Finished.
