### ISSUE TITLE
4.5.1 Post-release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2259]
These are chores that we should do before starting the cycle to reduce ripple effects if we do it in mid-cycle.

## Applies to all releases

> This list should be copied to versions in the future.

- [x] Bump `package.json` to `4.5.2-0`
- [x] Verify the build works minimally

## Applies to major/minor releases

> The following list does not applies to 4.5.1 because it is a patch release.

- [x] ~Bump all dev tool chain to latest version~
   - [x] ~All NPM packages (`@babel/*`, `jest`, `lerna`, `typescript`, `webpack`, etc)~
   - [x] ~Docker container for headless Chrome~
- [x] ~Run `npm audit fix` to make sure everything is fixed~
- [x] ~Bump React, Redux, and related dependencies to latest version~
- [x] ~Bump Adaptive Cards to latest version~

## Applies to 4.5.1 releases

No specific steps for 4.5.1.

**Comment by compulim** [comment]
Finished.
