### ISSUE TITLE
4.5.2 Post-release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2280]
These are chores that we should do before starting the cycle to reduce ripple effects if we do it in mid-cycle.

## Applies to all releases

> This list should be copied to versions in the future.

- [x] Bump `package.json` to `4.5.3-0`
- [x] ~Verify the build works minimally~
   - Does not apply to `qfe` release, because we cherry-pick from `master` to `qfe`, no modifications done to `master` (minus the version bump)

## Applies to major/minor releases

> The following list does not applies to 4.5.2 because it is a patch release.

- [ ] ~Bump all dev tool chain to latest version~
   - [ ] ~All NPM packages (`@babel/*`, `jest`, `lerna`, `typescript`, `webpack`, etc)~
   - [ ] ~Docker container for headless Chrome~
- [ ] ~Run `npm audit fix` to make sure everything is fixed~
- [ ] ~Bump React, Redux, and related dependencies to latest version~
- [ ] ~Bump Adaptive Cards to latest version~

## Applies to 4.5.2 releases

No specific steps for 4.5.2.

**Comment by compulim** [comment]
Done.
