### ISSUE TITLE
4.5.3 Release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2452]
This is a QFE and the related pull request is #2455.

## Build

1. [x] Update `CHANGELOG.md` to mark specific changes in `4.5.3`
1. [x] Run `npm version --no-git-tag-version 4.5.3`
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - The build number is `81869` and commit is `774e619`
1. [x] Download build artifacts
1. [x] Setup a new React app
   1. [x] `npx create-react-app app`
   1. [x] `npm install` the `.tgz` packages from artifact
   1. [x] Run the app and check if everything works
   1. [x] Check <meta> to see the version number should be `4.5.3` and not a pre-release
1. [x] Setup a new HTML file
   1. [x] Add `<script src="webchat-es5.js">`
   1. [x] Run the app and check if everything works
   1. [x] Check <meta> to see the version number should be `4.5.3` and not a pre-release

## Test

> The test should run against the build artifacts from Azure Pipelines.

> When testing against IE11, do not load Cognitive Services Speech Services, do include polyfills and `import 'react-app-polyfill/ie11'` in React app, and use HTTPS.

1. [x] ~Wait until Bot Framework SDK release 4.5 RC~
1. [x] ~Bump Bot Framework SDK in [MockBot](https://github.com/compulim/BotFramework-WebChat)~
1. [ ] Manual testing
   1. [x] All MockBot commands
      1. Type `help` to MockBot, it will list out all commands
      1. Try out each of the command, list out all failed below, if any
   1. [x] Speech scenarios
      1. [x] Happy path
         1. Click microphone button and say something
         1. Expect: bot to speak
         1. Expect: microphone to turn on automatically after bot message is spoken
      1. [x] ~Turning off microphone~
         1. (We currently have a bug on this route, before this patch release)
         1. Click microphone button and say something
         1. Expect: while your speech is getting recognized, the microphone button should turn red
         1. Expect: while the microphone button is red, you can click to stop it
         1. Expect: your speech interims should not be sent
      1. [x] ~Keyboard interrupted speech synthesis and recognition~
         1. (This one is not working, need a fix, but it is not a new bug, it wasn't working for some time)
         1. Click microphone button and say something
         1. While the bot is speaking, type something on the keyboard
         1. Expect: bot stop speaking immediately and microphone will not turn on by itself
      1. [x] Unrecognizable sound (or muted microphone)
         1. Click microphone button and do not say anything
         1. Expect: after a few seconds, the microphone button should be switched off by itself
      1. [x] Test on iOS devices
   1. [x] Connectivity scenarios
      1. [x] Airplane mode
      1. [x] Bad secret or token
1. [x] Test specific fixes related to `4.5.3`
   - [x] Generating thumbnail and attach as `attachments[].thumbnailUrl`
      - [x] PR [#2206](https://github.com/microsoft/BotFramework-WebChat/pull/2206)
      - [x] PR [#2262](https://github.com/microsoft/BotFramework-WebChat/pull/2262)
      - [x] PR [#2433](https://github.com/microsoft/BotFramework-WebChat/pull/2433)
      - [x] Under modern browsers
      - [x] Under IE11
      - [x] Test uploading a PNG
      - [x] Test uploading a non-image
   - [x] Accessibility fix for Emulator
      - [x] PR [#2423](https://github.com/microsoft/BotFramework-WebChat/pull/2423)
      - [x] Under Edge and Narrator
      - [x] Under Chrome and NVDA

## Release

1. [x] Make sure you are on `master` or `qfe` branch, run `git status` to check
1. [x] `git pull`
1. [x] `git tag v4.5.3`
1. [x] `git push -u upstream v4.5.3`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.5.3/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
1. [x] Kick off release to NPM
1. [x] Kick off release to CDN
   1. [ ] Send reminder email to approvers
1. [ ] Update [`servicingPlan.json`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/servicingPlan.json)
   - Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.5.3/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`

## Post-release check

1. [x] Setup a new React app using the package from NPM
1. [ ] Setup a new HTML file using the bundle from CDN

## Notification to interesting parties

- [ ] Notify related parties for the following fixes
   - [ ] Generating thumbnails
   - [x] Accessibility fix for emulator
   
### Changed

-  `bundle`: Bumped DirectLineJS to support metadata when uploading attachments, in PR [#2433](https://github.com/microsoft/BotFramework-WebChat/pull/2433)
   - [`botframework-directlinejs@0.11.5`](https://www.npmjs.com/package/botframework-directlinejs)
   - Removed DirectLineJS as a dev dependency for `component` because it was not referenced

### Fixed

-  Fix [#2248](https://github.com/microsoft/BotFramework-WebChat/issues/2248). Remove download links from user-uploaded attachment without thumbnails, by [@compulim](https://github.com/compulim) in PR [#2262](https://github.com/microsoft/BotFramework-WebChat/pull/2262)
-  Fix [Emulator:#1823](https://github.com/microsoft/BotFramework-Emulator/issues/1823). Fix Sendbox "Type your message" being read twice by AT, by [@corinagum](https://github.com/corinagum) in PR [#2423](https://github.com/microsoft/BotFramework-WebChat/pull/2423)
-  Fix [#2422](https://github.com/microsoft/BotFramework-WebChat/issues/2422). Store thumbnail URL using the activity's `attachment.thumbnailUrl` field, by [@compulim](https://github.com/compulim) in PR [#2433](https://github.com/microsoft/BotFramework-WebChat/pull/2433)

### Added

-  Make thumbnails when uploading GIF/JPEG/PNG and store it in `channelData.attachmentThumbnails`, by [@compulim](https://github.com/compulim), in PR [#2206](https://github.com/microsoft/BotFramework-WebChat/pull/2206), requires modern browsers with following features:
   - [Web Workers API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API)
   - [`createImageBitmap`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap)
   - [`MessageChannel`](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel)/[`MessagePort`](https://developer.mozilla.org/en-US/docs/Web/API/MessagePort)
   - [`OffscreenCanvas`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas)
      - Specifically [`OffscreenCanvas.getContext('2d')`](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/getContext)
-  Render thumbnail for image attachments using `activity.attachments[].thumbnailUrl`, by [@compulim](https://github.com/compulim) in PR [#2433](https://github.com/microsoft/BotFramework-WebChat/pull/2433)

**Comment by corinagum** [comment]
Closing as resolved: https://github.com/microsoft/BotFramework-WebChat/pull/2455
