### ISSUE TITLE
4.6.0 Post-release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2527]
These are chores that we should do before starting the cycle to reduce ripple effects if we do it in mid-cycle.

## Applies to all releases

> This list should be copied to versions in the future.

1. [x] Bump `package.json` to `4.6.1-0`
   - #2528
1. [x] Verify the build works minimally
1. [x] ~On QFE branch, make sure `CHANGELOG.md` is cherry-picked to `master`~

## Applies to major/minor releases

- [x] Bump all dev tool chain to latest version
   - [x] All NPM packages (`@babel/*`, `jest`, `lerna`, `typescript`, `webpack`, etc) (#2533)
   - [x] Docker container for headless Chrome (#2545)
- [x]  Run `npm audit fix` to make sure everything is fixed
- [x] ~Bump React, Redux, and related dependencies to latest version~
   - We are locking React to 16.8.6 unless another major feature released
- [x] ~Bump Adaptive Cards to latest version~
   - Currently, Adaptive Cards 1.2.3 is bugged

**Comment by corinagum** [comment]
working on verifying the builds

**Comment by compulim** [comment]
All items finished.
