### ISSUE TITLE
4.7.0/4.7.1 Release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2701]
# Checklist

## Build

1. [x] Bump to Bot Framework SDK release 4.7 RC4
   - https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder
1. [x] ~Update all samples to use `4.7.0`~
   - Moved to post-release checklist
1. [x] Update `CHANGELOG.md` to mark specific changes in `4.7.1`
1. [x] Run `npm version --no-git-tag-version 4.7.1`
   1. [x] Merge into `master`, the PR number is #2732
   1. Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - ~The build number is `95108` and commit is `b8f1639`~
      - Issue: Direct Line Speech adapter does not emit version number, fixed in #2706
   - ~The build number is `95227` and commit is `7d7a172ddda7df9d5a76dc45152eb198b07ee8a1`~
      - Issue: Minimal bundle fail because it was not expect `renderMarkdown` to be falsy
   - ~The build number is `95527` and commit is `781109312be8c614ad16bd8f954ccf1b50dfcd62`~
      - Issue: Missing `core-js` dependencies in `botframework-directlinespeech-sdk`
   - The build number is `95746` and commit is `cb37aa2`
1. [x] Download build artifacts
1. [x] Setup hosting apps
   1. [x] Hosting apps
      - [x] `create-react-app`
      - [x] `babel/standalone`
      - [x] `renderWebChat` with React loaded
         - [x] ES5 bundle (on IE11 and all browsers)
         - [x] Full bundle without ES5
         - [x] Minimal bundle (without speech)
         - [x] ES5 bundle with Direct Line Speech (on IE11 and all browsers)
      - [x] `renderWebChat` without React loaded
   1. [x] For each of the hosting scenario, verify
      - Web Chat is loaded
      - User can send a simple message
         - Bot will respond with a simple response
      - User can say a simple message using microphone
         - Bot will respond with a synthesized message
      - Bot can display an Adaptive Card (e.g. `card breakfast`)
         - (Don't use `herocard` because it is not using the middleware to register AC renderer)
      - Bot can send Markdown and displayed correctly
         - Type `markdown`
      - Check `<meta>` to see the version number should be `4.7.0` and not a pre-release
         - `[].map.call(document.querySelectorAll('head meta[name^="bot"]'), function (meta) { return [meta.name, meta.content].join('='); });`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] Manual testing on major browsers
   1. All MockBot commands
      - On each of the following browsers:
         - [x] Chrome
         - [x] Edge (UWP)
         - [x] Firefox
         - [x] IE11
         - [x] Macbook Safari
         - [x] iOS Safari
         - [x] Android Chrome
      1. Type `help` to MockBot, it will list out all commands
      1. Try out each of the command, list out all failed below, if any
   1. Speech scenarios
      - On each of the following browsers:
         - [x] Chrome
         - [x] Edge (UWP)
         - [x] Firefox
         - [x] Macbook Safari
         - [x] iOS Safari
         - [x] Android Chrome
      1. Happy path
         1. Click microphone button and say something
         1. Expect: bot to speak
         1. Expect: microphone to turn on automatically after bot message is spoken
      1. Turning off microphone
         1. Click microphone button and say something
         1. Expect: while your speech is getting recognized, the microphone button should turn red
         1. Expect: while the microphone button is red, you can click to stop it
         1. Expect: your speech interims should not be sent
      1. Keyboard interruption on speech synthesis
         1. Click microphone button and say something
         1. While the bot is speaking, type something on the keyboard
         1. Expect: bot stop speaking immediately and microphone will not turn on by itself
      1. Unrecognizable sound (or muted microphone)
         1. Click microphone button and do not say anything
         1. Expect: after a few seconds, the microphone button should be switched off by itself
      1. Recognition behavior after synthesis of "input hint expected"
         1. On all browsers including Safari, it should open microphone again and start recognizing
         1. Click on the microphone button should interrupt the synthesis
         1. Type on the keyboard should interrupt the synthesis
      1. Proactive message should be synthesized
         1. Say "proactive"
         1. Wait until both first and proactive message arrive, do not type on the keyboard in the meanwhile
         1. Expect: both the first and proactive message should be synthesized.
      1. Direct Line Speech: Simple speech recognition and synthesis
         1. Say "What's the weather?"
         1. Expect: bot should say, "here is the forecast of this week."
   1. (IE11) Direct Line Speech
      1. [x] Web Chat should work over Direct Line Speech channel, without microphone button
   1. [x] (Any) Connectivity scenarios
      1. [x] Airplane mode
      1. [x] Bad secret or token
1. [x] Test specific fixes related to `4.7.0` and previous releases
   
   - [x] (IE11) https://github.com/microsoft/BotFramework-WebChat/pull/2559 and https://github.com/microsoft/BotFramework-WebChat/pull/2719, ES5 bundle should work in IE11
      1. In IE11, run `01.b` sample, it should work
   - [x] (IE11) https://github.com/microsoft/BotFramework-WebChat/pull/2590 Invalid card should work in IE11
      1. In IE11, type `invalidCard`, it should render "Adaptive Card error" component
   - [x] (Any) https://github.com/microsoft/BotFramework-WebChat/pull/2593 Arabic support
      1. Set language to `ar-EG`, it should display in Arabic
   - [x] (All) https://github.com/microsoft/BotFramework-WebChat/pull/2613 Accessibility for Suggested Actions
      1. Chrome: Verify suggested actions is narrated as "..."
      1. Edge UWP: Verify suggested actions is narrated as "..."
      1. Firefox: Verify suggested actions is narrated as "..."
   - [x] (Any) https://github.com/microsoft/BotFramework-WebChat/pull/2631 Chinese localization
      1. Set language to `zh-HANS`, `zh-HANT` and `zh-YUE`, it should display in Chinese
   - [x] (Chrome) https://github.com/microsoft/BotFramework-WebChat/pull/2648 `AdaptiveCardsComposer` and `AdaptiveCardsContext`
      1. Make sure Smart Display sample works
   - [x] (Chrome) https://github.com/microsoft/BotFramework-WebChat/pull/2649 Smart Display sample
      1. Make sure Smart Display sample works
   - [x] (IE11) https://github.com/microsoft/BotFramework-WebChat/pull/2654 Including `endsWith` polyfill
      1. In IE11, run `01.b` sample, it should work
   - [x] (IE11) https://github.com/microsoft/BotFramework-WebChat/pull/2658 Markdown image should not show unnecessary padding in IE11
      1. Create a command in MockBot that shows a Markdown with a >= 1024x768 image
      1. In IE11, type the command to show the Markdown
   - [x] (Any) https://github.com/microsoft/BotFramework-WebChat/pull/2320 Adaptive Cards should use `speak` property for synthesis
      1. Say "What's the weather" in MockBot, you listen be able to listen to the second card saying "Flight KL0605 to San Fransisco has been delayed. It will not leave until 10:10 AM."
   - [x] (Any) https://github.com/microsoft/BotFramework-WebChat/pull/2331 Text sending out should be trimmed
      1. Type `ABC  ` (two spaces after the letters), open Network Tab and check the traffic, it should send `"ABC"` instead of `"ABC  "`
   - [x] (Any) https://github.com/microsoft/BotFramework-WebChat/pull/2332 Hide scroll to end button through style options
      1. Add a style options `hideScrollToEndButton: false` and the scroll to end button should be hidden
   - [x] (macOS) https://github.com/microsoft/BotFramework-WebChat/pull/2382 Button should be styled in Chrome on macOS
      1. Type `help` and the button shown should not be gradient color
   - [x] (Any) https://github.com/microsoft/BotFramework-WebChat/pull/2399 Allow fullscreen for videos
      1. Type `video youtube`, play the video, the full screen button should be clickable and will expand the video to full screen

## Release

1. [x] Make sure you are on `master` ~or `qfe`~ branch, run `git status` to check
1. [x] `git pull`
1. [x] `git tag v4.7.1`
1. [x] `git push -u upstream v4.7.1`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [x] Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.7.0/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [x] Attach assets including 3 JS files and 4 tarballs
      - JS bundle download from build artifacts
      - Tarballs download from npmjs
         - `curl -L -o botframework-directlinespeech-sdk-4.7.0.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.7.0.tgz`
         - `curl -L -o botframework-webchat-4.7.0.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.7.0.tgz`
         - `curl -L -o botframework-webchat-core-4.7.0.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.7.0.tgz`
         - `curl -L -o botframework-webchat-component-4.7.0.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.7.0.tgz`
1. [x] Kick off release to NPM
1. [x] Kick off release to CDN
   - Script build number is `57881`
   1. [x] Send reminder email to approvers
1. [x] Update [`servicingPlan.json`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/servicingPlan.json)
   - Add deprecation notes for previous versions
   - Subresource integrity hash from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.7.1
   - The PR is #2739

## Post-release check

- Hosting apps
   - NPM
      - [x] `create-react-app` using package from public NPM
         - [x] `npm uninstall botframework-webchat-*` (remove all tarballs)
         - [x] `npm install botframework-webchat@4.7.0` (just install the bundle package)
   - Bundle
      - Using `<script>` tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.7.0, with subresource integrity
      - [x] `babel/standalone` using package from CDN
      - [x] `renderWebChat` with React loaded using package from CDN
         - [x] ES5 bundle (on IE11 and all browsers)
         - [x] Full bundle without ES5
         - [x] Minimal bundle
      - [x] `renderWebChat` without React loaded using package from CDN

## Notification to interesting parties

- [x] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/236
- [x] Notify related parties for the following fixes
   - Cognitive Services Speech team
   - Microsoft Japan Web Apps team
   
# Changelog

### Changed

- Moved `core-js` from dev dependencies to dependencies in `botframework-directlinespeech-sdk` package, by [@tonyanziano](https://github.com/tonyanziano), in PR [#2727](https://github.com/microsoft/BotFramework-WebChat/pull/2727)

### Breaking changes

-  `adaptiveCardHostConfig` is being renamed to `adaptiveCardsHostConfig`
   -  If you are using the deprecated `adaptiveCardHostConfig`, we will rename it automatically

### Added

-  Resolves [#2539](https://github.com/Microsoft/BotFramework-WebChat/issues/2539), added React hooks for customization, by [@compulim](https://github.com/compulim), in the following PRs:
   -  PR [#2540](https://github.com/microsoft/BotFramework-WebChat/pull/2540): `useActivities`, `useReferenceGrammarID`, `useSendBoxShowInterims`
   -  PR [#2541](https://github.com/microsoft/BotFramework-WebChat/pull/2541): `useStyleOptions`, `useStyleSet`
   -  PR [#2542](https://github.com/microsoft/BotFramework-WebChat/pull/2542): `useLanguage`, `useLocalize`, `useLocalizeDate`
   -  PR [#2543](https://github.com/microsoft/BotFramework-WebChat/pull/2543): `useAdaptiveCardsHostConfig`, `useAdaptiveCardsPackage`, `useRenderMarkdownAsHTML`
   -  PR [#2544](https://github.com/microsoft/BotFramework-WebChat/pull/2544): `useAvatarForBot`, `useAvatarForUser`
   -  PR [#2547](https://github.com/microsoft/BotFramework-WebChat/pull/2547): `useEmitTypingIndicator`, `usePeformCardAction`, `usePostActivity`, `useSendEvent`, `useSendFiles`, `useSendMessage`, `useSendMessageBack`, `useSendPostBack`
   -  PR [#2548](https://github.com/microsoft/BotFramework-WebChat/pull/2548): `useDisabled`
   -  PR [#2549](https://github.com/microsoft/BotFramework-WebChat/pull/2549): `useSuggestedActions`
   -  PR [#2550](https://github.com/microsoft/BotFramework-WebChat/pull/2550): `useConnectivityStatus`, `useGroupTimestamp`, `useTimeoutForSend`, `useUserID`, `useUsername`
   -  PR [#2551](https://github.com/microsoft/BotFramework-WebChat/pull/2551): `useLastTypingAt`, `useSendTypingIndicator`, `useTypingIndicator`
   -  PR [#2552](https://github.com/microsoft/BotFramework-WebChat/pull/2552): `useFocusSendBox`, `useScrollToEnd`, `useSendBoxValue`, `useSubmitSendBox`, `useTextBoxSubmit`, `useTextBoxValue`
   -  PR [#2553](https://github.com/microsoft/BotFramework-WebChat/pull/2553): `useDictateInterims`, `useDictateState`, `useGrammars`, `useMarkActivityAsSpoken`, `useMicrophoneButton`, `useShouldSpeakIncomingActivity`, `useStartDictate`, `useStopDictate`, `useVoiceSelector`, `useWebSpeechPonyfill`
   -  PR [#2554](https://github.com/microsoft/BotFramework-WebChat/pull/2554): `useRenderActivity`, `useRenderAttachment`
   -  PR [#2644](https://github.com/microsoft/BotFramework-WebChat/pull/2644): Added `internal/useWebChatUIContext` for cleaner code
-  Bring your own Adaptive Cards package by specifying `adaptiveCardsPackage` prop, by [@compulim](https://github.com/compulim) in PR [#2543](https://github.com/microsoft/BotFramework-WebChat/pull/2543)
-  Fixes [#2597](https://github.com/microsoft/BotFramework-WebChat/issues/2597). Modify `watch` script to `start` and add `tableflip` script for throwing `node_modules`, by [@corinagum](https://github.com/corinagum) in PR [#2598](https://github.com/microsoft/BotFramework-WebChat/pull/2598)
-  Adds Arabic Language Support, by [@midineo](https://github.com/midineo), in PR [#2593](https://github.com/microsoft/BotFramework-WebChat/pull/2593)
-  Adds `AdaptiveCardsComposer` and `AdaptiveCardsContext` for composability for Adaptive Cards, by [@compulim](https://github.com/compulim), in PR [#2648](https://github.com/microsoft/BotFramework-WebChat/pull/2648)
-  Adds Direct Line Speech support, by [@compulim](https://github.com/compulim) in PR [#2621](https://github.com/microsoft/BotFramework-WebChat/pull/2621)
   -  Adds [`microsoft-cognitiveservices-sdk@1.8.1`](https://npmjs.com/package/microsoft-cognitiveservices-speech-sdk), in PR [#2704](https://github.com/microsoft/BotFramework-WebChat/pull/2704)
-  Fixes [#2692](https://github.com/microsoft/BotFramework-WebChat/issues/2692). Rename sample 17 to 17.a, by [@corinagum](https://github.com/corinagum) in PR [#2695](https://github.com/microsoft/BotFramework-WebChat/pull/2695)

### Fixed

-  Fixes [#2565](https://github.com/microsoft/BotFramework-WebChat/issues/2565). Fixed Adaptive Card host config should generate from style options with default options merged, by [@compulim](https://github.com/compulim) in PR [#2566](https://github.com/microsoft/BotFramework-WebChat/pull/2566)
-  Resolves [#2337](https://github.com/microsoft/BotFramework-WebChat/issues/2337). Remove Cognitive Services Preview warning, by [@corinagum](https://github.com/corinagum) in PR [#2578](https://github.com/microsoft/BotFramework-WebChat/pull/2578)
-  Fixes [#2559](https://github.com/microsoft/BotFramework-WebChat/issues/2559). De-bump remark and strip-markdown, by [@corinagum](https://github.com/corinagum) in PR [#2576](https://github.com/microsoft/BotFramework-WebChat/pull/2576)
-  Fixes [#2512](https://github.com/microsoft/BotFramework-WebChat/issues/2512). Adds check to ensure Adaptive Card's content is an Object, by [@tdurnford](https://github.com/tdurnford) in PR [#2590](https://github.com/microsoft/BotFramework-WebChat/pull/2590)
-  Fixes [#1780](https://github.com/microsoft/BotFramework-WebChat/issues/1780), [#2277](https://github.com/microsoft/BotFramework-WebChat/issues/2277), and [#2285](https://github.com/microsoft/BotFramework-WebChat/issues/2285). Make Suggested Actions accessible, Fix Markdown card in carousel being read multiple times, and label widgets of Connectivity Status and Suggested Actions containers, by [@corinagum](https://github.com/corinagum) in PR [#2613](https://github.com/microsoft/BotFramework-WebChat/pull/2613)
-  Fixes [#2608](https://github.com/microsoft/BotFramework-WebChat/issues/2608). Focus will return to sendbox after clicking New Messages or a Suggested Actions button, by [@corinagum](https://github.com/corinagum) in PR [#2628](https://github.com/microsoft/BotFramework-WebChat/pull/2628)
-  Resolves [#2597](https://github.com/microsoft/BotFramework-WebChat/issues/2597). Modify `watch` script to `start` and add `tableflip` script for throwing `node_modules`, by [@corinagum](https://github.com/corinagum) in PR [#2598](https://github.com/microsoft/BotFramework-WebChat/pull/2598)
-  Resolves [#1835](https://github.com/microsoft/BotFramework-WebChat/issues/1835). Adds `suggestedActionLayout` to `defaultStyleOptions`, by [@spyip](https://github.com/spyip), in PR [#2596](https://github.com/microsoft/BotFramework-WebChat/pull/2596)
-  Resolves [#2331](https://github.com/microsoft/BotFramework-WebChat/issues/2331). Updated timer to use React Hooks, by [@spyip](https://github.com/spyip) in PR [#2546](https://github.com/microsoft/BotFramework-WebChat/pull/2546)
-  Resolves [#2620](https://github.com/microsoft/BotFramework-WebChat/issues/2620). Adds Chinese localization files, by [@spyip](https://github.com/spyip) in PR [#2631](https://github.com/microsoft/BotFramework-WebChat/pull/2631)
-  Fixes [#2639](https://github.com/microsoft/BotFramework-WebChat/issues/2639). Fix passed in prop time from string to boolean, by [@corinagum](https://github.com/corinagum) in PR [#2640](https://github.com/microsoft/BotFramework-WebChat/pull/2640)
-  `component`: Updated timer to use functional component, by [@spyip](https://github.com/spyip) in PR [#2546](https://github.com/microsoft/BotFramework-WebChat/pull/2546)
-  Fixes [#2651](https://github.com/microsoft/BotFramework-WebChat/issues/2651). Add `ends-with` string module to es5 bundle, by [@corinagum](https://github.com/corinagum) in PR [#2654](https://github.com/microsoft/BotFramework-WebChat/pull/2654)
-  Fixes [#2658](https://github.com/microsoft/BotFramework-WebChat/issues/2658). Fix rendering of markdown images in IE11, by [@corinagum](https://github.com/corinagum) in PR [#2659](https://github.com/microsoft/BotFramework-WebChat/pull/2659)
-  Fixes [#2662](https://github.com/microsoft/BotFramework-WebChat/issues/2662) and [#2666](https://github.com/microsoft/BotFramework-WebChat/issues/2666). Fix various issues related to Direct Line Speech, by [@compulim](https://github.com/compulim) in PR [#2671](https://github.com/microsoft/BotFramework-WebChat/pull/2671)
   -  Added triple-buffering to reduce pops/cracks.
   -  Enable Safari by upsampling to 48000 Hz.
   -  Support detailed output format on Web Chat side.
-  Fixes [#2700](https://github.com/microsoft/BotFramework-WebChat/issues/2700). Enable `<SayComposer>` and Adaptive Cards in recompose story, in PR [#2649](https://github.com/microsoft/BotFramework-WebChat/pull/2649)
   -  Moved `<SayComposer>` from `<BasicTranscript>` to `<Composer>`
   -  Moved WebSpeechPonyfill patching code from `<BasicTranscript>` to `<Composer>`
-  Fixes [#2699](https://github.com/microsoft/BotFramework-WebChat/issues/2699). Disable speech recognition and synthesis when using Direct Line Speech under IE11, by [@compulim](https://github.com/compulim), in PR [#2649](https://github.com/microsoft/BotFramework-WebChat/pull/2649)
-  Fixes [#2709](https://github.com/microsoft/BotFramework-WebChat/issues/2709). Reduce wasted render of activities by memoizing partial result of `<BasicTranscript>`, by [@compulim](https://github.com/compulim) in PR [#2710](https://github.com/microsoft/BotFramework-WebChat/pull/2710)
-  Fixes [#2710](https://github.com/microsoft/BotFramework-WebChat/issues/2710). Suggested actions container should persist for AT, by [@corinagum](https://github.com/corinagum) in PR [#2710](https://github.com/microsoft/BotFramework-WebChat/pull/2710)
-  Fixes [#2718](https://github.com/microsoft/BotFramework-WebChat/issues/2718). Add `Object.is` polyfill for IE11, by [@compulim](https://github.com/compulim) in PR [#2719](https://github.com/microsoft/BotFramework-WebChat/pull/2719)
-  Fixes [#2723](https://github.com/microsoft/BotFramework-WebChat/issues/2723). Fix `renderMarkdown` should not be called if it is `undefined` in minimal bundle, by [@compulim](https://github.com/compulim) in PR [#2724](https://github.com/microsoft/BotFramework-WebChat/pull/2724)

### Changed

-  Bumped all dependencies to latest version, by [@compulim](https://github.com/compulim), in PR [#2533](https://github.com/microsoft/BotFramework-WebChat/pull/2533) and PR [#2621](https://github.com/microsoft/BotFramework-WebChat/pull/2621)
   -  Development dependencies
      -  Root package
         -  `@azure/storage-blob@12.0.0`
         -  `@babel/plugin-proposal-class-properties@7.5.5`
         -  `@babel/plugin-proposal-object-rest-spread@7.6.2`
         -  `@babel/plugin-transform-runtime@7.6.2`
         -  `@babel/preset-env@7.6.3`
         -  `@babel/preset-react@7.6.3`
         -  `@babel/preset-typescript@7.6.0`
         -  `@babel/runtime@7.6.3`
         -  `babel-jest@24.9.0`
         -  `core-js@3.3.6`
         -  `coveralls@3.0.7`
         -  `husky@3.0.9`
         -  `jest-image-snapshot@2.11.0`
         -  `jest@24.9.0`
         -  `lerna@3.18.3`
         -  `lint-staged@9.4.2`
         -  `selenium-webdriver@4.0.0-alpha.5`
         -  `serve-handler@6.1.2`
      -  Other packages
         -  `@babel/cli@7.6.4`
         -  `@babel/core@7.6.4`
         -  `@babel/plugin-proposal-class-properties@7.5.5`
         -  `@babel/plugin-proposal-object-rest-spread@7.6.2`
         -  `@babel/plugin-transform-runtime@7.6.2`
         -  `@babel/preset-env@7.6.3`
         -  `@babel/preset-react@7.6.3`
         -  `@babel/preset-typescript@7.6.0`
         -  `@types/node@12.12.3`
         -  `@types/react@16.9.11`
         -  `@typescript-eslint/eslint-plugin@2.6.0`
         -  `@typescript-eslint/parser@2.6.0`
         -  `babel-plugin-istanbul@5.2.0`
         -  `concurrently@5.0.0`
         -  `copy-webpack-plugin@5.0.4`
         -  `eslint-plugin-prettier@3.1.1`
         -  `eslint-plugin-react-hooks@2.2.0`
         -  `eslint-plugin-react@7.16.0`
         -  `eslint@6.6.0`
         -  `http-proxy-middleware@0.20.0`
         -  `jest@24.9.0`
         -  `terser-webpack-plugin@2.2.1`
         -  `typescript@3.6.4`
         -  `webpack-cli@3.3.10`
         -  `webpack@4.41.2`
   -  Production dependencies
      -  `core`
         -  `@babel/runtime@7.6.3`
         -  `jsonwebtoken@8.5.1`
         -  `math-random`
         -  `redux-saga@1.1.1`
         -  `simple-update-in@2.1.1`
      -  `bundle`
         -  `@babel/runtime@7.6.3`
         -  `core-js@3.3.6`
         -  `markdown-it@10.0.0`
         -  `memoize-one@5.1.1`
         -  `sanitize-html@1.19.0`
         -  `url-search-params-polyfill@7.0.0`
      -  `component`
         -  `bytes@3.1.0`
         -  `memoize-one@5.1.1`
         -  `react-dictate-button@1.2.1`
         -  `react-redux@7.1.1`
         -  `remark@11.0.1`
         -  `sanitize-html@1.20.1`
         -  `simple-update-in@2.1.1`
         -  `strip-markdown@3.1.1`
      -  `embed`
         -  `@babel/runtime@7.6.3`
         -  `core-js@3.3.6`
-  `component`: Bumps [`adaptivecards@1.2.3`](https://npmjs.com/package/adaptivecards), by [@corinagum](https://github.com/corinagum) in PR [#2523](https://github.com/microsoft/BotFramework-WebChat/pull/2532)
-  Bumps Chrome in Docker to 78.0.3904.70, by [@spyip](https://github.com/spyip) in PR [#2545](https://github.com/microsoft/BotFramework-WebChat/pull/2545)
-  `bundle`: Webpack will now use `webpack-stats-plugin` instead of `webpack-visualizer-plugin`, by [@compulim](https://github.com/compulim) in PR [#2584](https://github.com/microsoft/BotFramework-WebChat/pull/2584)
   -  This will fix [#2583](https://github.com/microsoft/BotFramework-WebChat/issues/2583) by not bringing in transient dependency of React
   -  To view the bundle stats, browse to https://chrisbateman.github.io/webpack-visualizer/ and drop the file `/packages/bundle/dist/stats.json`
-  Resolves [#2674](https://github.com/microsoft/BotFramework-WebChat/issues/2674). Update embed docs, by [@corinagum](https://github.com/corinagum), in PR [#2696](https://github.com/microsoft/BotFramework-WebChat/pull/2696)

### Samples

-  [Clear Conversation After Idle](https://microsoft.github.io/BotFramework-WebChat/17.b.clear-after-idle/), by [@tdurnford](https://github.com/tdurnford), in PR [#2375](https://github.com/microsoft/BotFramework-WebChat/pull/2375)
-  [Smart Display](https://microsoft.github.io/BotFramework-WebChat/24.customization-smart-display/), by [@compulim](https://github.com/compulim), in PR [#2649](https://github.com/microsoft/BotFramework-WebChat/pull/2649)

**Comment by compulim** [comment]
Add release works has been done.
