### ISSUE TITLE
4.7.1 Post-release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2708]
These are chores that we should do before starting the cycle to reduce ripple effects if we do it in mid-cycle.

Tips: 

- [x] Clean your repo before start
- [x] Remove node_modules from all folder
   - [x] git clean -fdx
- [x] 	Never delete package-lock.json	
- [x] If you mess it up, tableflip and redo
- [x] 	In component/package.json
   - [x] Remove reference to botframework-webchat-core by hand-modifying package.json
   - [x] Then, npm install
   - [x] Then, add those references back by hand-modifying package.json
   - [x] Also for other packages with similar dependencies

## Applies to all releases

> This list should be copied to versions in the future.

1. [X] Bump `package.json` to `4.7.2-0`
   - The PR number is #2738
1. [x] ~On QFE branch, make sure `CHANGELOG.md` is cherry-picked to `master`~

## Applies to major/minor releases

- [x] Update all samples to use `4.7.1`
- [x] Bump all dependencies to latest version
   - [x] All NPM packages (`@babel/*`, `jest`, `lerna`, `typescript`, `webpack`, etc) (#2533)
   - [x] Docker container for headless Chrome (#2545)
   - Don't bump the following packages
      - `react`, `react-dom`, `redux`, `redux-saga`
         - Locking down for app compatibility
      - `remark` and `strip-markdown`
         - `remark` don't work under IE11
         - Go to the repos and see if this is fixed or by design
      - `serve`
      - `rxjs` on `playground`
- [x]  Run `npm audit fix` to make sure everything is fixed
- [x]  Test under IE11 to make sure all dependencies are working
