### ISSUE TITLE
4.8.0 Post-release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#2962]
These are chores that we should do before starting the cycle to reduce ripple effects if we do it in mid-cycle.

Tips: 

- Clean your repo before start
- Remove node_modules from all folder
   - `git clean -fdx`
- Never delete `package-lock.json	`
- If you mess it up, tableflip and redo
- In `component/package.json`
   - Remove reference to `botframework-webchat-core` by hand-modifying `package.json`
   - Then, `npm install`
   - Then, add those references back by hand-modifying `package.json`
   - Also for other packages with similar dependencies

## Applies to all releases

> This list should be copied to versions in the future.

1. [x] Bump `package.json` to `4.8.1-0`
   - The PR number is #2982
1. [x] ~On QFE branch, make sure `CHANGELOG.md` is cherry-picked to `master`~

## Applies to major/minor releases

- [x] Bump all dependencies to latest version
   - [x] All NPM packages (`@babel/*`, `jest`, `lerna`, `typescript`, `webpack`, etc) (#2985)
   - [x] Docker container for headless Chrome (#2992)
   - Don't bump the following packages
      - `react`, `react-dom`, `redux`, `redux-saga`
         - Locking down for app compatibility
      - `remark` and `strip-markdown`
         - `remark` don't work under IE11
         - Go to the repos and see if this is fixed or by design
      - `serve`
      - `rxjs` on `playground`
      - `microsoft-cognitiveservices-speech-sdk`
- [x] Run `npm audit fix` to make sure everything is fixed
   - The PR is #3017
- [x] Test under IE11 to make sure all dependencies are working
- [x] Update [`servicingPlan.json`](https://github.com/microsoft/BotFramework-WebChat/blob/master/packages/embed/servicingPlan.json)
   - Add deprecation notes for previous versions
   - Subresource integrity hash from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.8.0
   - The PR is #2986
- [ ] Update all samples to use `4.8.0`
   - The PR is #2983
