### ISSUE TITLE
Adapter Test: Move adapter tests related resources to our own subscriptions

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3044]
## Background

Need to ping Tom to create a new subscription and we move resources over.

## Tasks

- [ ] Ping Tom to create a new subscription
- [ ] Ask @youyu16 to move the resources to the new subscription
- [ ] Update the CD pipeline to publish to the new subscription
