### ISSUE TITLE
Adapter Test: Review the test code

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3045]
## Tasks

- [x] @youyu16 create a new branch and make a PR so we can comment on
- [x] @compulim comment on the PR
- [x] @youyu16 merge the PR back to master
- [x] @compulim to do an interactive PR review

**Comment by compulim** [comment]
Done.
