### ISSUE TITLE
4.8.1 Release Checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3103]
# Checklist

## Build

1. [x] ~Bump to Bot Framework SDK release 4.8.1 RC~
   - https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder
   - We are releasing QFE 4.8.1, no need to bump
1. [x] Update `CHANGELOG.md` to mark specific changes in `4.8.1`
1. [x] Run `npm version --no-git-tag-version 4.8.1`
   - [x] Merged into `qfe`
   - Commit is `e640dc5`
   - Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - The build number is `120273` and commit is `e640dc5`
1. [x] Run `BotFramework-WebChat-Release-Testing` CI pipeline
   - Set `GitHub.FullBranch` to `refs/heads/qfe`
   - The build number is `120276` and commit is `d9a30ed`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] Manual testing on major browsers using `webchat-release-testing`
   - [x] Chrome
   - [x] Edge (Anaheim)
   - [x] Edge (UWP)
   - [x] Firefox
   - [x] IE11
   - [x] Macbook Safari
   - [x] iOS Safari
   - [x] Android Chrome
1. [x] Test specific fixes related to `4.8.1` and previous releases
   

## Release

1. [x] Make sure you are on ~`master` or~ `qfe` branch, run `git status` to check
1. [x] `git pull`
1. [x] Verify `/package.json`, `/package-lock.json`, and `CHANGELOG.md` has a version of `4.8.1`
1. [x] `git log`
   - Verify the latest commit is `XXX`
1. [x] `git tag v4.8.1`
1. [x] `git push -u upstream v4.8.1`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [x] Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.8.1/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [x] Attach assets including 3 JS files and 4 tarballs
      - You can copy the artifacts from `webchat-release-testing/drops`
      - Tarballs download from npmjs
         ```
         curl -L -o botframework-directlinespeech-sdk-4.8.1.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.8.1.tgz
         curl -L -o botframework-webchat-4.8.1.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.8.1.tgz
         curl -L -o botframework-webchat-core-4.8.1.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.8.1.tgz
         curl -L -o botframework-webchat-component-4.8.1.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.8.1.tgz
         ```
1. [x] Kick off release to NPM
   - The release number is `2044` (`Release-20`), build number is `120273`
1. [x] Kick off release to CDN
   - The release number is `2045` (`Release-24`), build number is `120273`
   - Script build number is `105174`
   1. [x] Send reminder email to approvers

## Post-release check

- Clone `webchat-release-testing`
   - `01.create-react-app`
      1. [x] Nuke `01.create-react-app/node_modules`
      1. [x] `npm install botframework-webchat@4.8.1` (just install the bundle package)
   - Others
      -  [x] Using script tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.8.1, with subresource integrity
         ```
         <script
            crossorigin="anonymous"
            integrity="sha384-"
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"
         ></script>
         ```

## Notification to interesting parties

- [ ] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/264
- [ ] Notify related parties for the following fixes
   
# Changelog

(To be copied)
