### ISSUE TITLE
4.9.1 Release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3216]
# Checklist

## Build

1. [ ] Bump to Bot Framework SDK release 4.9.2
   - ~https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder~
   - https://www.npmjs.com/package/botbuilder/v/4.9.2
1. [ ] Update `CHANGELOG.md` to mark specific changes in `4.9.1`
1. [ ] Run `npm version --no-git-tag-version 4.9.1`
   - [ ] Merged into `master`, the PR number is #XXX
   - Commit is `XXX`
   - Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [ ] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - The build number is `XXX` and commit is `XXX`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [ ] Manual testing on major browsers using `webchat-release-testing`
   - [ ] (Update the version numbers below)
   - [ ] Chrome 81.0.4044.138
   - [ ] Edge (Anaheim) 84.0.512.0
   - [ ] Edge (UWP) 44.19041.1.0
   - [ ] Firefox 76.0.1
   - [ ] IE11
   - [ ] macOS Safari 13.0.3 (15608.3.10.1.4)
   - [ ] iOS Safari 13.4.1
   - [ ] Android Chrome 81.0.4044.138
1. [ ] Test specific fixes related to `4.9.1` and previous releases
   - [ ] (Look at [`CHANGELOG.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md) and list out PRs that were not covered with automated tests)

## Release

1. [ ] Make sure you are on `master` ~or `qfe`~ branch, run `git status` to check
1. [ ] `git pull`
1. [ ] Verify `/package.json`, `/package-lock.json`, and `CHANGELOG.md` has a version of `4.9.1`
1. [ ] `git log`
   - Verify the latest commit is `XXX`
1. [ ] `git tag v4.9.1`
1. [ ] `git push -u upstream v4.9.1`
   - You do not need to kick off a build again, use the previous build
1. [ ] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [ ] Subresource Integrity can be generated by `curl https://cdn.botframework.com/botframework-webchat/4.9.1/webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [ ] Attach assets including 3 JS files and 4 tarballs
      - You can copy the artifacts from `webchat-release-testing/drops`
      - Tarballs download from npmjs
         ```
         curl -L -o botframework-directlinespeech-sdk-4.9.1.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.9.1.tgz
         curl -L -o botframework-webchat-4.9.1.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.9.1.tgz
         curl -L -o botframework-webchat-core-4.9.1.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.9.1.tgz
         curl -L -o botframework-webchat-component-4.9.1.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.9.1.tgz
         ```
1. [ ] Kick off release to NPM
   - The build number is `XXX`, release number is `XXX` and commit is `XXX`
1. [ ] Kick off release to CDN
   - The build number is `XXX`, release number is `XXX` and commit is `XXX`
   - Script build number is `131156`
   1. [ ] Send reminder email to approvers

## Post-release check

- [ ] Clone `webchat-release-testing`
   - `01.create-react-app`
      1. [ ] Nuke `01.create-react-app/node_modules`
      1. [ ] `npm install botframework-webchat@4.9.1` (just install the bundle package)
   - Others
      -  Using script tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.9.1, with subresource integrity
         ```
         <script
            crossorigin="anonymous"
            integrity="sha384-"
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"
         ></script>
         ```

## Notification to interesting parties

- [ ] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/XXX
- [ ] Notify related parties for the following fixes
   
# Changelog

> To be copied from `CHANGELOG.md`.
