### ISSUE TITLE
4.9.2 Release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3302]
# Checklist

## Build

1. [x] ~Bump MockBot to Bot Framework SDK release 4.9.2~
   - ~https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder~
   - ~https://www.npmjs.com/package/botbuilder/v/4.9.2~
   - We are not bumping for patch release
1. [x] Update `CHANGELOG.md` to mark specific changes in `4.9.2`
1. [x] Run `npm version --no-git-tag-version 4.9.2`
   - [x] Merged into `master`, the PR number is #3304
   - Commit is `e0b9ccc`
   - Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - Pipeline name is `BotFramework-WebChat-daily`
   - The build number is `146184` and commit is `e0b9ccc`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] Manual testing on major browsers using `webchat-release-testing`
   - [x] Chrome 83.0.4103.116
   - [x] Edge (Anaheim) 83.0.478.61
   - [x] Edge (UWP) 44.18362.449.0
   - [x] Firefox 78.0.2
   - [x] IE11
   - [x] macOS Safari 13.0.3 (15608.3.10.1.4)
      - Update version number
      - DLSpeech: Web Socket connection to `westus2.convai.speech.microsoft.com` closed instantly after connected, it also repro on previous versions of Web Chat (failed on 4.9.0, 4.8.1)
         - As it also repro on 4.9.0 and 4.8.1, I think this is service-side issue
   - [x] iOS Safari 13.4.1
      - Update version number
   - [x] Android Chrome 83.0.4103.96
      - Update version number
1. [x] Test specific fixes related to `4.9.2` and previous releases
   - [x] (Look at [`CHANGELOG.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md) and list out PRs that were not covered with automated tests)
   - [x] #3276
   - [x] #3287

## Release

1. [x] Make sure you are on `master` ~or `qfe`~ branch, run `git status` to check
1. [x] `git pull`
1. [x] Verify `/package.json`, `/package-lock.json`, and `CHANGELOG.md` has a version of `4.9.2`
1. [x] `git log`
   - Verify the latest commit is `e0b9ccc`
1. [x] `git tag v4.9.2`
1. [x] `git push -u upstream v4.9.2`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [x] Subresource Integrity can be generated by
      - From CDN: `curl -H 'Accept-Encoding: gzip' https://cdn.botframework.com/botframework-webchat/4.9.2/webchat.js | gunzip - | openssl dgst -sha384 -binary | openssl base64 -A`
      - From local: `cat webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [x] Attach assets including 3 JS files, `stats.json` and 4 tarballs
      - You can copy the artifacts from `webchat-release-testing/drops`
      - Tarballs download from npmjs
         ```
         curl -L -o botframework-directlinespeech-sdk-4.9.2.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.9.2.tgz
         curl -L -o botframework-webchat-4.9.2.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.9.2.tgz
         curl -L -o botframework-webchat-core-4.9.2.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.9.2.tgz
         curl -L -o botframework-webchat-component-4.9.2.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.9.2.tgz
         ```
1. [x] Kick off release to NPM
   - Release name is `[[PROD]]Push-WebChat-to-npmjs`
   - The build number is `146184`, release number is `2384` and commit is `e0b9ccc`
   - Retain the build indefinitely
1. [x] Kick off release to CDN
   1. [x] Prepare the email for approval
   - Release name is `[[PROD]]Push-WebChat-to-Prod-CDN-with-approval`
   - The build number is `146184`, release number is `2389` and commit is `e0b9ccc`
   - Script build number is `131156`
   1. [x] Send reminder email to approvers
   - Retain the build indefinitely

## Post-release check

- [x] Test using `webchat-release-testing`
   - [x] Clone https://github.com/corinagum/WebChat-release-testing/
   - [x] `01.create-react-app`
      1. [x] Nuke `01.create-react-app/node_modules`
      1. [x] `npm install botframework-webchat@4.9.2` (just install the bundle package)
   - [x] Others
      -  Using script tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.9.2, with subresource integrity
         ```
         <script
            crossorigin="anonymous"
            integrity="sha384-"
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"
         ></script>
         ```

## Notification to interested parties

- [x] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/308
- [x] Notify related parties for the following fixes
   - [x] CDC
   - [x] OC
   - [x] Pooja
   
# Changelog

### Added

-  Resolves [#3182](https://github.com/microsoft/BotFramework-WebChat/issues/3182). Added stacked suggested actions height properties, by [@corinagum](https://github.com/corinagum), in PR [#3235](https://github.com/microsoft/BotFramework-WebChat/pull/3235)
-  Localized strings in Cantonese (`yue`), by [@compulim](https://github.com/compulim), in PR [#3289](https://github.com/microsoft/BotFramework-WebChat/pull/3289)

### Fixes

-  Fixes [#3265](https://github.com/microsoft/BotFramework-WebChat/issues/3265). Fix styling specificity regression on microphone button, by [@corinagum](https://github.com/corinagum) in PR [#3276](https://github.com/microsoft/BotFramework-WebChat/pull/3276)
-  Fixes [#3279](https://github.com/microsoft/BotFramework-WebChat/issues/3279). Fix relative timestamp errored out when showing a time before yesterday, by [@compulim](https://github.com/compulim) in PR [#3282](https://github.com/microsoft/BotFramework-WebChat/pull/3282)
-  Fixes [#3236](https://github.com/microsoft/BotFramework-WebChat/issues/3236), by [@compulim](https://github.com/compulim) in PR [#3287](https://github.com/microsoft/BotFramework-WebChat/pull/3287)
   -  Isolated screen reader only live region for incoming activities and added a new `<ScreenReaderActivity>` component
   -  Removed screen reader text for activities outside of live region, including `<CarouselFilmstrip>`, `<StackedLayout>`, `<TextContent>`, and `<Timestamp>`
   -  Updated some accessibility texts
   -  Rectified activities render order by delaying activities with `replyToId` that reference an activity which is not ACK-ed, for up to 5 seconds
   -  Disabled widgets will have `tabindex="-1"` set, instead of `disabled` attribute
   -  Remove `tabindex="-1"` from Adaptive Cards container
   -  Hide activities of type `invoke`
-  Fixes [#3294](https://github.com/microsoft/BotFramework-WebChat/issues/3294). Fix blank screen on missing middlewares, by [@compulim](https://github.com/compulim) in PR [#3295](https://github.com/microsoft/BotFramework-WebChat/pull/3295)
-  Fixes [#3297](https://github.com/microsoft/BotFramework-WebChat/issues/3297). Fix `className` prop is not honored in `<ReactWebChat>`, by [@compulim](https://github.com/compulim) in PR [#3300](https://github.com/microsoft/BotFramework-WebChat/pull/3300)

### Samples

-  Resolves [#3218](https://github.com/microsoft/BotFramework-WebChat/issues/3218) and [#2811](https://github.com/microsoft/BotFramework-WebChat/issues/2811). Adds documentation on reconnecting to a conversation in minimizable sample, by [@corinagum](https://github.com/corinagum), in PR [#3239](https://github.com/microsoft/BotFramework-WebChat/pull/3239)

**Comment by corinagum** [comment]
Closing as complete.
