### ISSUE TITLE
4.10.0 Release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3417]
# Checklist

## Build

1. [x] Bump MockBot to Bot Framework SDK release 4.10.0
   - https://www.npmjs.com/package/botbuilder/v/4.10.0
   - We are not bumping for patch release
1. [x] Bump `botframework-directlinejs` to `0.13.0`
   - PR is #3418 and #3419
1. [x] Bump to `4.10.0`
   - [x] Update `CHANGELOG.md` to mark specific changes in `4.10.0`
   - [x] Run `npm version --no-git-tag-version 4.10.0`
   - [x] Merged into `master`, the PR number is #3420
   - Commit is `9b346b8`
   - Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - Pipeline name is `BotFramework-WebChat-daily`
   - The build number is [`157901`](https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=157901&view=results) and commit is `9b346b8`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] Manual testing on major browsers using `webchat-release-testing`
   - [x] Chrome 84.0.4147.125
   - [x] Edge (Anaheim) 84.0.522.61
   - [x] Edge (UWP) 44.19041.423.0
   - [x] Firefox 79.0
   - [x] IE11 11.450.19041.0 (11.0.205 KB4571687)
   - [x] macOS Safari 13.1.1 (15609.2.9.1.2)
      - DLSpeech: Web Socket connection to `westus2.convai.speech.microsoft.com` closed instantly after connected, it also repro on previous versions of Web Chat (failed on 4.9.0, 4.8.1)
         - https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221
   - [x] iOS Safari 13.6.1
   - [x] Android Chrome 84.0.4147.125
1. [x] Test specific fixes related to `4.10.0` and previous releases
   - [x] (N/A) ~(Look at [`CHANGELOG.md`](https://github.com/microsoft/BotFramework-WebChat/blob/master/CHANGELOG.md) and list out PRs that were not covered with automated tests)~

## Release

1. [x] Make sure you are on `master` ~or `qfe`~ branch, run `git status` to check
1. [x] `git pull`
1. [x] Verify `/package.json`, `/package-lock.json`, and `CHANGELOG.md` has a version of `4.10.0`
1. [x] `git log`
   - Verify the latest commit is `9b346b8`
1. [x] `git tag v4.10.0`
1. [x] `git push -u upstream v4.10.0`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [x] Subresource Integrity can be generated by
      - From CDN: `curl -H 'Accept-Encoding: gzip' https://cdn.botframework.com/botframework-webchat/4.10.0/webchat.js | gunzip - | openssl dgst -sha384 -binary | openssl base64 -A`
      - From local: `cat webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [x] Attach assets including 3 JS files, `stats.json` and 4 tarballs
      - You can copy the artifacts from `webchat-release-testing/drops`
      - Tarballs download from npmjs
         ```
         curl -L -o botframework-directlinespeech-sdk-4.10.0.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.10.0.tgz
         curl -L -o botframework-webchat-4.10.0.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.10.0.tgz
         curl -L -o botframework-webchat-core-4.10.0.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.10.0.tgz
         curl -L -o botframework-webchat-component-4.10.0.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.10.0.tgz
         ```
1. [x] Kick off release to NPM
   - Release name is `[[PROD]]Push-WebChat-to-npmjs`
   - The build number is `157901`, release number is `2442` and commit is `9b346b8`
   - Retain the build indefinitely
1. [x] Kick off release to CDN
   1. [x] Prepare the email for approval
   - Release name is `[[PROD]]Push-WebChat-to-Prod-CDN-with-approval`
   - The build number is `157901`, release number is `2443` and commit is `9b346b8`
   - Script build number is `131156`
   1. [x] Send reminder email to approvers
   - Retain the build indefinitely

## Post-release check

- [x] Test using `webchat-release-testing`
   - [x] Clone https://github.com/corinagum/WebChat-release-testing/
   - [x] `01.create-react-app`
      1. [x] Nuke `01.create-react-app/node_modules`
      1. [x] `npm install botframework-webchat@4.10.0` (just install the bundle package)
   - [x] Others
      -  Using script tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.10.0, with subresource integrity
         ```
         <script
            crossorigin="anonymous"
            integrity="sha384-"
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"
         ></script>
         ```

## Notification to interested parties

- [x] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/XXX
- [x] Notify related parties for the following fixes
   - [x] SDK team
   - [x] Omnichannel
   - [x] Pooja
   
# Changelog
