### ISSUE TITLE
4.11.0 Release checklist

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#3566]
# Checklist

## Build

1. [x] ~Bump MockBot to Bot Framework SDK release 4.11.0~
   - https://www.npmjs.com/package/botbuilder/v/4.11.0
   - We are not bumping for patch release
1. [x] ~Bump `botframework-directlinejs` to `0.13.0`~
   - PR is XXX
   - We did not bump `botframework-directlinejs`
1. [x] Bump to `4.11.0`
   - [x] Update `CHANGELOG.md` to mark specific changes in `4.11.0`
   - [x] Run `npm version --no-git-tag-version 4.11.0`
   - [x] Merged into `master`, the PR number is #3588
   - Commit is `009a27e`
   - Do not merge any other unrelated changes after this PR. Any other PR merged, will need to be re-tested
1. [x] Run daily pipeline manually, set "generate release version number" to `true`
   - (This will not push to NPM or CDN)
   - Pipeline name is `BotFramework-WebChat-daily`
   - The build number is [`181956`](https://fuselabs.visualstudio.com/BotFramework-WebChat/_build/results?buildId=181956&view=results) and commit is `009a27e`

## Test

> The test should run against the build artifacts from Azure Pipelines.

1. [x] Manual testing on major browsers using `webchat-release-testing`
   - [x] Chrome 86.0.4240.111
   - [x] Edge (Anaheim) 86.0.622.56
   - [x] Edge (UWP) 44.20241.1000.1 (EdgeHTML 18.20241)
   - [x] Firefox 82.0.2
   - [x] IE11 (Windows 10 20246.1)
   - [x] macOS Safari 13.1.3 (15609.4.1)
      - DLSpeech: Web Socket connection to `westus2.convai.speech.microsoft.com` closed instantly after connected, it also repro on previous versions of Web Chat (failed on 4.9.0, 4.8.1)
         - https://github.com/microsoft/cognitive-services-speech-sdk-js/issues/221
   - [x] iOS Safari 14.1
   - [x] Android Chrome 86.0.4240.110
1. [x] Test specific fixes related to `4.11.0` and previous releases
   
   - [x] Accessibility: screen reader will now read attachment details

## Release

1. [x] Make sure you are on `master` ~or `qfe`~ branch, run `git status` to check
1. [x] `git pull`
1. [x] Verify `/package.json`, `/package-lock.json`, and `CHANGELOG.md` has a version of `4.11.0`
1. [x] `git log`
   - Verify the latest commit is `009a27e`
1. [x] `git tag v4.11.0`
1. [x] `git push -u upstream v4.11.0`
   - You do not need to kick off a build again, use the previous build
1. [x] Create a new GitHub release, copy entries from `CHANGELOG.md`
   - [x] Subresource Integrity can be generated by
      - From CDN: `curl -H 'Accept-Encoding: gzip' https://cdn.botframework.com/botframework-webchat/4.11.0/webchat.js | gunzip - | openssl dgst -sha384 -binary | openssl base64 -A`
      - From local: `cat webchat.js | openssl dgst -sha384 -binary | openssl base64 -A`
   - [x] Attach assets including 3 JS files, `stats.json` and 5 tarballs
      - You can copy the artifacts from `webchat-release-testing/drops`
      - Tarballs download from npmjs
         ```
         curl -L -o botframework-directlinespeech-sdk-4.11.0.tgz https://registry.npmjs.org/botframework-directlinespeech-sdk/-/botframework-directlinespeech-sdk-4.11.0.tgz
         curl -L -o botframework-webchat-4.11.0.tgz https://registry.npmjs.org/botframework-webchat/-/botframework-webchat-4.11.0.tgz
         curl -L -o botframework-webchat-core-4.11.0.tgz https://registry.npmjs.org/botframework-webchat-core/-/botframework-webchat-core-4.11.0.tgz
         curl -L -o botframework-webchat-api-4.11.0.tgz https://registry.npmjs.org/botframework-webchat-api/-/botframework-webchat-api-4.11.0.tgz
         curl -L -o botframework-webchat-component-4.11.0.tgz https://registry.npmjs.org/botframework-webchat-component/-/botframework-webchat-component-4.11.0.tgz
         ```
1. [x] Kick off release to NPM
   - Release name is `[[PROD]]Push-WebChat-to-npmjs`
   - The build number is `181956`, release number is `2532` and commit is `009a27e`
   - Retain the build indefinitely
1. [x] Kick off release to CDN
   1. [x] Prepare the email for approval
   - Release name is `[[PROD]]Push-WebChat-to-Prod-CDN-with-approval`
   - The build number is `181956`, release number is `2540` and commit is `009a27e`
   - Script build number is `131156` (this is fixed)
   1. [x] Send reminder email to approvers
   - Retain the build indefinitely

## Post-release check

- [x] Test using `webchat-release-testing`
   1. [x] Clone https://github.com/corinagum/WebChat-release-testing/
   1. [x] `01.create-react-app`
      1. [x] Nuke `01.create-react-app/node_modules`
      1. [x] `npm install`
      1. [x] `npm install botframework-webchat@4.11.0` (just install the bundle package)
      1. [x] `npm run build`
   1. [x] Others
      -  Using script tags from https://github.com/microsoft/BotFramework-WebChat/releases/tag/v4.11.0, with subresource integrity
         ```
         <script
            crossorigin="anonymous"
            integrity="sha384-vkX1C8fopQ2J+lXKsoiEUWsLnvq9bfoS54SzU4P1iM+AafCMLUL9sbC2NY0ktBnL"
            src="https://cdn.botframework.com/botframework-webchat/latest/webchat-es5.js"
         ></script>
         ```
   1. [x] `npx serve` (at repo root)
   1. [x] Go to http://localhost:5000/ to test, including IE11

## Notification to interested parties

- [x] Update partner page on Adaptive Cards doc
   - https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
   - PR at https://github.com/MicrosoftDocs/AdaptiveCards/pull/XXX
- [x] Notify related parties for the following fixes
   - [x] SDK team
   - [ ] Omnichannel
   - [x] Pooja
- [ ] Update root README.md with feature notes
- [x] Update https://github.com/microsoft/BotFramework-sdk/issues/6086
   
# Changelog

### Added

-  Resolves [#3281](https://github.com/microsoft/BotFramework-WebChat/issues/3281). Added documentation on speech permissions for Cordova apps on Android, by [@corinagum](https://github.com/corinagum), in PR [#3508](https://github.com/microsoft/BotFramework-WebChat/pull/3508)
-  Resolves [#3316](https://github.com/microsoft/BotFramework-WebChat/issues/3316). Refactored platform-neutral APIs into the new `api` package, to be reused on React Native component, in PR [#3543](https://github.com/microsoft/BotFramework-WebChat/pull/3543) by [@compulim](https://github.com/compulim)
   -  The new layering is `core` -> `api` -> `component` (HTML-only) -> `bundle`
   -  Includes composition mode, platform-neutral React hooks, and localization resources
   -  Most hooks are available in the new `api` package. Some hooks are only available on the existing `component` package, due to their platform dependency or coupling with visual components. For example, Web Worker, 2D canvas, `useMicrophoneButton*` are not available on the `api` package
   -  Most implementations of middleware are only available in `component` package due to their coupling with visual components or platform features. Some implementations, (e.g. card action middleware and activity grouping middleware) are available on `api` package. For example:
      -  Carousel layout and stacked layout is only available on `component` package due to their coupling with their respective visual components
      -  For card action middleware, `imBack`, `messageBack` and `postBack` actions are available on `api` package, but `call`, `openUrl` and other platform-dependent actions are only available on `component` package
   -  `activityMiddleware`, `attachmentMiddleware`, etc, now support arrays for multiple middleware

### Fixed

-  Fixes [#3489](https://github.com/microsoft/BotFramework-WebChat/issues/3489). [Accessibility]: Fix AT saying 'Bot undefined said', by [@corinagum](https://github.com/corinagum) in PR [#3524](https://github.com/microsoft/BotFramework-WebChat/pull/3524)
-  Fixes [#3547](https://github.com/microsoft/BotFramework-WebChat/issues/3547). [Accessibility]: Add attachment middleware for screen reader, by [@compulim](https://github.com/compulim) in PR [#3548](https://github.com/microsoft/BotFramework-WebChat/pull/3548)
-  Fixes [#3371](https://github.com/microsoft/BotFramework-WebChat/issues/3371). [Accessibility]: Add alt property for image in HeroCards, by [@corinagum](https://github.com/corinagum) in PR [#3541](https://github.com/microsoft/BotFramework-WebChat/pull/3541)
-  Fixes [#3310](https://github.com/microsoft/BotFramework-WebChat/issues/3310). Add quantity, tap and text field to ReceiptCards, by [@corinagum](https://github.com/corinagum) in PR [#3541](https://github.com/microsoft/BotFramework-WebChat/pull/3541)
-  Fixes [#3514](https://github.com/microsoft/BotFramework-WebChat/issues/3514). Fix PoliCheck language errors, by [@corinagum](https://github.com/corinagum) in PR [#3545](https://github.com/microsoft/BotFramework-WebChat/pull/3545)
-  Fixes [#3537](https://github.com/microsoft/BotFramework-WebChat/issues/3537). [Accessibility]: Ensure `aria-roledescription` is only used on elements with implicit/explicit role based off of [WAI ARIA role attributes](https://www.w3.org/WAI/PF/aria/roles), by [@corinagum](https://github.com/corinagum) in PR [#3551](https://github.com/microsoft/BotFramework-WebChat/pull/3551) and [#3583](https://github.com/microsoft/BotFramework-WebChat/pull/3583)
-  Fixes [#3431](https://github.com/microsoft/BotFramework-WebChat/issues/3431). Activities should not be delayed due to missing activity of type "typing", by [@compulim](https://github.com/compulim) in PR [#3554](https://github.com/microsoft/BotFramework-WebChat/pull/3554)
-  Fixes [#3574](https://github.com/microsoft/BotFramework-WebChat/issues/3574). Creates workaround for Cognitive Services Speech SDK 1.13.1 regarding removed support of macOS/iOS, by [@compulim](https://github.com/compulim) in PR [#3576](https://github.com/microsoft/BotFramework-WebChat/pull/3576)
-  Fixes [#3570](https://github.com/microsoft/BotFramework-WebChat/issues/3570). Adaptive Card `speak` property should be narrated by screen reader, by [@compulim](https://github.com/compulim) in PR [#3573](https://github.com/microsoft/BotFramework-WebChat/pull/3573) and PR [#3584](https://github.com/microsoft/BotFramework-WebChat/pull/3584)
-  Fixes [#3571](https://github.com/microsoft/BotFramework-WebChat/issues/3571). Error box should be hidden for Adaptive Card renderer when running in production mode, by [@compulim](https://github.com/compulim) in PR [#3573](https://github.com/microsoft/BotFramework-WebChat/pull/3573)

### Changed

-  Bumped development dependency [`node-fetch@2.6.1`](https://npmjs.com/package/node-fetch) in PR [#3467](https://github.com/microsoft/BotFramework-WebChat/pull/3467) by [@dependabot](https://github.com/dependabot)
-  Bumped Cognitive Services Speech SDK to 1.13.1, by [@compulim](https://github.com/compulim) in PR [#3432](https://github.com/microsoft/BotFramework-WebChat/pull/3432)
   -  [`microsoft-cognitiveservices-speech-sdk@1.13.1`](https://npmjs.com/package/microsoft-cognitiveservices-speech-sdk)

### Samples

-  Fixes [#3526](https://github.com/microsoft/BotFramework-WebChat/issues/3526). Add info on composition mode in sample 06.d, by [@corinagum](https://github.com/corinagum) in PR [#3541](https://github.com/microsoft/BotFramework-WebChat/pull/3541)

**Comment by corinagum** [comment]
Closing as complete
