### ISSUE TITLE
Accessibility issues found during ADMINS testing

### ISSUE THREAD

**Issue by nfreear** [microsoft/BotFramework-WebChat#3655]
Dear WebChat​ developers,

We've been using WebChat in a chatbot for the _Microsoft AI for Accessibility_-funded [ADMINS project](https://iet.open.ac.uk/projects/admins), here at The Open University.

For our text and speech-enabled Web-based Chatbot we are particularly concerned about accessibility, so accessibility experts (_Chetz Colwell_, and _Steven Price_) have done evaluations and testing for us.

I will be creating bug reports for individual accessibility issues, and linking to this ticket for clarity.

I'm happy to discuss the issues, possible solutions, and would like to get involved in pull requests where appropriate.

I should also acknowledge that they found plenty that was positive about the accessibility of our Chat-bot, and by extension the _WebChat_ library!

I hope this helps,

Nick

---
`[added]`

## Motivation / context

A note on my motivation for raising the issues ...

I've mostly implemented workarounds and fixes as we went along for the accessibility issues that Chetz, Steven and I identified.

The purpose(s) of raising the bugs are so:

  1. We can reduce the number of workarounds (_hacks?_) built into our implementation;

  2. The "WebChat" library has a greater level of accessibility "built-in", by default, without other developers having to code workarounds (many may not be aware of the issues, or the knowledge to fix them);

---
* [Accessibility spreadsheet/report](https://docs.google.com/spreadsheets/d/1GDPUZMYPaPbQO4_Tb0szdDgRH35_8hopP-nAdZXED2c/edit#gid=113117542).

## Screenshots

`[n/a]`

## Version

 * WebChat.js version :~ 4.10.1;
     - JS :~ https://cdn.botframework.com/botframework-webchat/4.10.1/webchat.js;
 * (Speech SDK version :~ 1.13.1)
     - (JS :~ 
https://cdn.jsdelivr.net/npm/microsoft-cognitiveservices-speech-sdk@1.13.1/distrib/browser/microsoft.cognitiveservices.speech.sdk.bundle-min.js)

## Describe the bug

_Work-in-progress!_

 * [x] — #3656, Missing `tabindex` on video player start button;
 * [ ] — #3657, CSS `outline` is missing when WebChat buttons, text fields and links receive focus;
 * [x] — PR #3641, Add suggested actions flow layout by @compulim — _good job_!
 * [ ] — #3658, PR #3669, WebChat container's role should not always be `complementary`;
 * [ ] — <s>#3659</s>, #3087, Provide more context when links open in a new window/tab;
 * [ ] — #?

[Bug]

**Comment by gabog** [comment]
Hi @cwhitten, can you please triage this one? 

Thanks

**Comment by nfreear** [comment]
Hi,

Just noting that I've added a section on _Motivation_ to the above description, as I realise that my point-of-view may not be clear.

Nick

**Comment by cwhitten** [comment]
Hi @nfreear - the team will prioritize these items in our upcoming release. Please follow your linked issues for updates.

**Comment by srinaath** [comment]
closing this ticket as its contents are covered in linked tickets
