### ISSUE TITLE
Flush new UIs for better bot response

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-WebChat#4856]
### Is your feature request related to a problem?

Related to #4846.

```[tasklist]
### Tasks
- [x] Rename to `OrgThemeSchema`
- [x] [packages/component/src/types/internal/TypeOfArray.ts](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-cec713bb724ef8fc7226bf555b4f05a3d69d98194c288f53d7855b496ee86b33) may not need either `T[]` or `Array<T>`
- [x] [packages/component/src/providers/ModalDialog/private/Popover.tsx:L45](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-a157220a68b3f83b29fd827088930955c1e235bcfa8b533d1382cc5265e8f133) may be just `onClose={onDismissRef.current}`
- [x] [packages/component/src/providers/ModalDialog/ModalDialogComposer.tsx](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-c971d99ab8793361c0e96281e4b6899dfdc8abc7d8f68dc3eed778df40c42a35) may not need the `undefined` in args
- [x] [packages/component/src/Styles/StyleSet/ThumbButton.ts:L50](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-f66e0be1bfd19670df99b1b5532b42be5a9c2128d7a2fcc3ad8e0d5dfc51c4cd) remove commented code
- [x] Add a `tokens.colorForeground` for shorthanding to `var(--webchat__color--accent)`
- [x] [packages/component/src/Styles/StyleSet/ThumbButton.ts](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-f66e0be1bfd19670df99b1b5532b42be5a9c2128d7a2fcc3ad8e0d5dfc51c4cd) remove/rename all `var(--pva__*)`
- [x] [packages/component/src/ActivityStatus/private/Feedback/Feedback.tsx:L18](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-c865f732f55875719268593983dba2bd1058cdd78cc80f9e4351747df94b8f5b) remove `undefined` in args
- [x] [packages/component/src/ActivityStatus/private/Feedback/Feedback.tsx](https://github.com/microsoft/BotFramework-WebChat/pull/4846/files/24c17dfc1a8c34b9ec5ae99c7e7dc3d0909076e6#diff-c865f732f55875719268593983dba2bd1058cdd78cc80f9e4351747df94b8f5b) use `setSelectedVoteAction` directly
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
