### ISSUE TITLE
Update samples

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#621]
# Background

Bring better coding style for `samples` folder.

# Tasks

* [ ] Add React samples
* [ ] Clean up existing samples
* [ ] Make sure we have samples for every entrypoints
  * [ ] `<iframe>`
  * [ ] JavaScript dist packages
  * [ ] React with package from npm registry

# Coding style

For clean up, I also suggest we should have consistency coding styles. At least samples for now:

* Indent with 2 spaces
* Prefer `const`/`let` over `var`
* Single quotes `'` for strings and backtick for string composition and complicated concatenation
* Implicitly add `type="text/javascript"` for `<script>` and `type="text/css"` for `<style>`/`<link>`
* CSS `font-family` should be single-quoted, `font-family: 'Segoe UI';` over `font-family: Segoe UI;`
* Map constructor have their members sorted, prefer `{ abc: 123, def: 456 }`, over `{ def: 456, abc: 123 }`

## Additional coding styles up for comment

And RFC for these coding styles:

### Align `:` and `=` vertically

```js
directLine: {
  domain: params['domain'],
  secret: params['s'],
  token: params['t'],
  webSocket: params['webSocket'] && params['webSocket'] === 'true'
}
```

Should become

```js
directLine: {
  domain   : params['domain'],
  secret   : params['s'],
  token    : params['t'],
  webSocket: params['webSocket'] && params['webSocket'] === 'true'
}
```

**Comment by danmarshall** [comment]
This is cool William! Can I propose a feature? I think it would be easy for everyone if we use VSCode's "autoformat" feature. This way we let the tool do the work to deliver consistency. There is a keyboard shortcut: ALT+SHIFT+F

**Comment by compulim** [comment]
Sure, will try adding VSCode workspace settings. We need VSCode extension for vertical colon alignments.

**Comment by eanders-MS** [comment]
I'm partial to just going with VSCode's generic formatting, unless it looks really broken which can happen in some cases. I'd like to avoid the need for extra plugins.

**Comment by billba** [comment]
I don't understand what this means:

> Implicitly add type="text/javascript" for <script> and type="text/css" for <style>/<link>

Either you don't add them, or you explicitly add them. In HTML 5 you can skip them both, and that's been working out fine...

**Comment by compulim** [comment]
I mean explicit, my bad.

**Comment by billba** [comment]
@compulim to what end? By which I mean, "solving what problem?" Is there a major browser (inc. IE) that requires the extra info?

**Comment by GeekTrainer** [comment]
@compulim FWIW, to what @billba is saying, [W3 Schools](https://www.w3schools.com/htmL/html5_syntax.asp) (which I'd say is as good a resource as any) says the `type` attribute is optional, and leaves it off their examples in their style guide.
