### ISSUE TITLE
Accessibility push

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-WebChat#723]
* [x] #724 Add `aria-label` to chatbox
* [x] #726 Add `aria-label` to upload, send, and speak buttons
* [x] #727 Make upload and speak button tabbable
* [x] #726 Add `role` to upload, send, and speak buttons
* [x] #728 Notify user after message has been sent/received
* [x] #727 Focus indicator for all buttons
* [x] #738 Update brand and timestamp color
* [x] #747 Instructions for overriding locale
